// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCWFiA5IxvPPuOwcQTBJQVDrKFOOTJZR4',
    appId: '1:100266383107:web:ccde6d9a6791eaca773b36',
    messagingSenderId: '100266383107',
    projectId: 'playbyplay-7cc1b',
    authDomain: 'playbyplay-7cc1b.firebaseapp.com',
    storageBucket: 'playbyplay-7cc1b.firebasestorage.app',
    measurementId: 'G-XSM6DD9BYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm5ZxRXuGp26zeoZ7ndoIM-aL9lvedl-A',
    appId: '1:100266383107:android:cf53a6285b659d15773b36',
    messagingSenderId: '100266383107',
    projectId: 'playbyplay-7cc1b',
    storageBucket: 'playbyplay-7cc1b.firebasestorage.app',
  );
}
