// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCawQfEXmnmBbYvpUc1afY-6MzVqGu6QF0',
    appId: '1:431365543284:web:dummy_web_id', // Note: Web App ID wasn't in google-services.json, using a synthetically valid structure for offline build verification
    messagingSenderId: '431365543284',
    projectId: 'local-league-live',
    authDomain: 'local-league-live.firebaseapp.com',
    storageBucket: 'local-league-live.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCawQfEXmnmBbYvpUc1afY-6MzVqGu6QF0',
    appId: '1:431365543284:android:8df07e50f05b669b198821',
    messagingSenderId: '431365543284',
    projectId: 'local-league-live',
    storageBucket: 'local-league-live.firebasestorage.app',
  );
}
